import React from "react";
import { useRouter } from "next/router";

function CommentId({ indComment }) {
  const router = useRouter();
  return (
    <div>
      <h2>
        Individual Comments generated by getStaticPaths for route -{" "}
        {router.query.commentId}
      </h2>
      <h4>
        {indComment.id}.{indComment.name}
      </h4>
      <p>{indComment.body}</p>
    </div>
  );
}

export default CommentId;

export async function getStaticPaths() {
  return {
    paths: [
      { params: { commentId: "1" } },
      { params: { commentId: "2" } },
      { params: { commentId: "3" } },
    ],
    fallback: "blocking",
  };
}

export async function getStaticProps(context) {
  const { params } = context;
  const res = await fetch(
    `https://jsonplaceholder.typicode.com/comments/${params.commentId}`
  );
  const data = await res.json();

  console.log(
    `getStaticPaths - fallback:'blocking' generating page - /comments/${params.commentId}`
  );

  return {
    props: {
      indComment: data,
    },
  };
}
